basePath: /api/v1
definitions:
  dto.CountryResponse:
    properties:
      code:
        example: CA
        type: string
      currency:
        example: $
        type: string
      name:
        example: Canada
        type: string
    type: object
  entities.Trip:
    properties:
      Budget:
        example: 2000.12
        type: number
      CountryId:
        example: 1
        type: integer
      CreatedAt:
        example: "2023-05-29"
        type: string
      DeletedAt:
        example: "2023-05-29"
        type: string
      Description:
        example: sample-description
        type: string
      EndDateTime:
        example: "2023-08-29"
        type: string
      ID:
        example: 1
        type: integer
      Name:
        example: sample-name
        type: string
      StartDateTime:
        example: "2023-05-29"
        type: string
      UpdatedAt:
        example: "2023-05-29"
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a pocket-mate server api
  title: Pocket Mate API
  version: 1.0.0
paths:
  /country:
    get:
      consumes:
      - application/json
      description: get a list of all available countires
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.CountryResponse'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get all country
      tags:
      - country
  /trip:
    get:
      consumes:
      - application/json
      description: get trip
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Trip'
        "400":
          description: Bad Request
      summary: Get all trip
      tags:
      - trip
swagger: "2.0"
