basePath: /api/v1
definitions:
  dto.BaseResponseDTO:
    properties:
      message:
        example: message
        type: string
    type: object
  dto.CountryResponseDTO:
    properties:
      code:
        example: CA
        type: string
      currency:
        example: $
        type: string
      name:
        example: Canada
        type: string
    type: object
  dto.ErrorResponseDTO:
    properties:
      error_message:
        example: error message
        type: string
    type: object
  dto.TokenDTO:
    properties:
      token:
        example: abc.abc.abc
        type: string
      token_type:
        example: Bearer
        type: string
    type: object
  dto.TripRequestDTO:
    properties:
      budget:
        example: 2000.12
        type: number
      countryId:
        example: 1
        type: integer
      description:
        example: sample-description
        type: string
      endDateTime:
        example: "2023-08-29"
        type: string
      name:
        example: sample-name
        type: string
      startDateTime:
        example: "2023-05-29"
        type: string
    required:
    - budget
    - countryId
    - description
    - endDateTime
    - name
    - startDateTime
    type: object
  dto.TripResponseDTO:
    properties:
      budget:
        example: 2000.12
        type: number
      countryId:
        example: 1
        type: integer
      description:
        example: sample-description
        type: string
      endDateTime:
        example: "2023-08-29"
        type: string
      id:
        example: 1
        type: integer
      name:
        example: sample-name
        type: string
      startDateTime:
        example: "2023-05-29"
        type: string
    type: object
  dto.TripStatusResponseDTO:
    properties:
      current:
        items:
          $ref: '#/definitions/dto.TripResponseDTO'
        type: array
      future:
        items:
          $ref: '#/definitions/dto.TripResponseDTO'
        type: array
      past:
        items:
          $ref: '#/definitions/dto.TripResponseDTO'
        type: array
    type: object
  dto.UserRequestDTO:
    properties:
      Email:
        example: test@email.com
        type: string
      Password:
        example: test-password
        type: string
    required:
    - Email
    - Password
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a pocket-mate server api
  title: Pocket Mate API
  version: 1.0.0
paths:
  /countries:
    get:
      consumes:
      - application/json
      description: get a list of all available countires
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.CountryResponseDTO'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
      summary: Get all country
      tags:
      - country
  /trips:
    get:
      consumes:
      - application/json
      description: get trip
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.TripStatusResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
      security:
      - bearer: []
      summary: get trip
      tags:
      - trip
    post:
      consumes:
      - application/json
      description: register trip
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: register trip
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.TripRequestDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.BaseResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
      security:
      - bearer: []
      summary: register trip
      tags:
      - trip
  /trips/{id}:
    delete:
      consumes:
      - application/json
      description: delete trip
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.BaseResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
      security:
      - bearer: []
      summary: delete trip
      tags:
      - trip
    put:
      consumes:
      - application/json
      description: update trip
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: update trip
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.TripRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.BaseResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
      security:
      - bearer: []
      summary: update trip
      tags:
      - trip
  /user:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: User registration
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UserRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.BaseResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
      summary: User registration
      tags:
      - user
  /user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: User login
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UserRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.TokenDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
      summary: Login
      tags:
      - user
swagger: "2.0"
