version: '3.8'

services:
  db:
    image: mysql:9.6
    restart: always
    container_name: 'db'
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: 'pm'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - dev_network
volumes:
  db:
    driver: local