version: '3.8'

services:
  db:
    image: mysql:8.0.20
    restart: always
    container_name: 'pocket-db'
    ports:
      - 3305:3306
    environment:
      MYSQL_DATABASE: 'pm'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ../data:/var/lib/mysql
volumes:
  db:
    driver: local