name: build_and_push

on:
  release:
    types: [published]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: ./server/docker/Dockerfile.dev
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/pocket-mate-server:latest
            ${{ secrets.DOCKER_REGISTRY }}/pocket-mate-server:${{ github.REF_NAME }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/pocket-mate-server:latest
          cache-to: type=inline
          build-args: |
            APP_URL=${{ secrets.APP_URL }}
            ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}
            ACCESS_TOKEN_EXPIRED_AT=${{ secrets.ACCESS_TOKEN_EXPIRED_AT }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_ADDR=${{ secrets.DB_ADDR }}
