name: Go Test

on:
  pull_request:
    branches: [main]
    paths:
      - "server/**"

env:
  DB_DATABASE: test
  DB_USER: root
  DB_PASSWORD: root

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
          cache: false
      - name: Set up MySQL
        run: |
          echo "Set up MySQL"
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Database migration
        working-directory: ./server
        run: |
          curl -s https://packagecloud.io/install/repositories/golang-migrate/migrate/script.deb.sh | sudo bash
          apt-get update
          apt-get install -y migrate
          migrate -path ./migration -database "mysql://${{ env.DB_USER }}:${{ env.DB_PASSWORD }}@tcp(localhost:3306)/${{ env.DB_DATABASE }}" up

      - name: run test
        working-directory: ./server
        run: make test
